Implementing tv show aggregate credits
jdrouet/tmdb-api pull request #81
Opened 2024-04-01 14:38 UTC by agmbk

2024-04-02 08:40 UTC, jdrouet requested changes
Just a single suggestion to avoid code duplication

2024-04-02 08:40 UTC, jdrouet commented on src/tvshow/aggregate_credits.rs
> +pub struct CastPerson {
Maybe we should introduce a `Person` struct that we could use everywhere.

2024-04-13 19:22 UTC, agmbk commented
Is it OK ?

2025-04-13 18:58 UTC, jdrouet approved these changes

2025-04-13 19:06 UTC, closed without merging